version: "3.8"
services:
  app:
    container_name: fineAnts_app
    platform: linux/amd64
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      PROFILE: local
      TZ: Asia/Seoul
      DB_HOST: fineAnts_db
      DB_PORT: 3306
      DB_DATABASE: fineAnts
      DB_USERNAME: root
      DB_PASSWORD: password1234!
      REDIS_HOST: fineAnts_redis
      REDOS_PORT: 6379
    depends_on:
      - redis
      - db
    networks:
      - spring-net
  db:
    container_name: fineAnts_db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password1234!
      - MYSQL_ROOT_PASSWORD=password1234!
      - MYSQL_DATABASE=fineAnts
    command:
      - '--local-infile=1'
    networks:
      - spring-net
  redis:
    container_name: fineAnts_redis
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - spring-net
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail:/etc/promtail
      - ./logs:/var/log
    env_file:
      - ./secret/promtail/.env
    command:
      - -config.file=/etc/promtail/config.yaml
      - -config.expand-env=true
networks:
  spring-net:
    driver: bridge
